server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio
    password: portfolio
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: info

app:
  github:
    username: amannkumar
    token: ${GITHUB_TOKEN:}
  leetcode:
    username: amannkumar
